// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  projectId: __t.u64().name("project_id"),
  phaseId: __t.u64().name("phase_id"),
  phaseContext: __t.string().name("phase_context"),
  completedWork: __t.string().name("completed_work"),
  remainingWork: __t.string().name("remaining_work"),
  decisions: __t.string(),
  blockers: __t.string(),
  nextAction: __t.string().name("next_action"),
  mentalContext: __t.string().name("mental_context"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
