// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  auditId: __t.u64(),
  auditStatus: __t.string(),
  requirementScores: __t.string(),
  integrationScores: __t.string(),
  flowScores: __t.string(),
  techDebtItems: __t.string(),
  roadmapContent: __t.string(),
  requirementsContent: __t.string(),
};
