// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  milestoneId: __t.u64(),
  version: __t.string(),
  name: __t.string(),
  shippedDate: __t.string(),
  phaseCount: __t.u64(),
  planCount: __t.u64(),
  requirementCount: __t.u64(),
  accomplishments: __t.string(),
  status: __t.string(),
};
