// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  projectId: __t.u64(),
  phaseId: __t.u64(),
  phaseContext: __t.string(),
  completedWork: __t.string(),
  remainingWork: __t.string(),
  decisions: __t.string(),
  blockers: __t.string(),
  nextAction: __t.string(),
  mentalContext: __t.string(),
};
