// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import DeleteConfigReducer from "../delete_config_reducer";
import DeleteContinueHereReducer from "../delete_continue_here_reducer";
import DeleteMustHaveReducer from "../delete_must_have_reducer";
import DeletePhaseReducer from "../delete_phase_reducer";
import DeletePhaseContextReducer from "../delete_phase_context_reducer";
import DeletePlanReducer from "../delete_plan_reducer";
import DeletePlanSummaryReducer from "../delete_plan_summary_reducer";
import DeletePlanTaskReducer from "../delete_plan_task_reducer";
import DeleteProjectReducer from "../delete_project_reducer";
import DeleteProjectStateReducer from "../delete_project_state_reducer";
import DeleteRequirementReducer from "../delete_requirement_reducer";
import DeleteResearchReducer from "../delete_research_reducer";
import DeleteVerificationReducer from "../delete_verification_reducer";
import InsertMustHaveReducer from "../insert_must_have_reducer";
import InsertPhaseReducer from "../insert_phase_reducer";
import InsertPhaseContextReducer from "../insert_phase_context_reducer";
import InsertPlanReducer from "../insert_plan_reducer";
import InsertPlanSummaryReducer from "../insert_plan_summary_reducer";
import InsertPlanTaskReducer from "../insert_plan_task_reducer";
import InsertProjectReducer from "../insert_project_reducer";
import InsertRequirementReducer from "../insert_requirement_reducer";
import InsertResearchReducer from "../insert_research_reducer";
import InsertVerificationReducer from "../insert_verification_reducer";
import SeedProjectReducer from "../seed_project_reducer";
import UpdateMustHaveReducer from "../update_must_have_reducer";
import UpdatePhaseReducer from "../update_phase_reducer";
import UpdatePhaseContextReducer from "../update_phase_context_reducer";
import UpdatePlanReducer from "../update_plan_reducer";
import UpdatePlanSummaryReducer from "../update_plan_summary_reducer";
import UpdatePlanTaskReducer from "../update_plan_task_reducer";
import UpdateProjectReducer from "../update_project_reducer";
import UpdateRequirementReducer from "../update_requirement_reducer";
import UpdateResearchReducer from "../update_research_reducer";
import UpdateVerificationReducer from "../update_verification_reducer";
import UpsertConfigReducer from "../upsert_config_reducer";
import UpsertContinueHereReducer from "../upsert_continue_here_reducer";
import UpsertProjectStateReducer from "../upsert_project_state_reducer";

export type DeleteConfigParams = __Infer<typeof DeleteConfigReducer>;
export type DeleteContinueHereParams = __Infer<typeof DeleteContinueHereReducer>;
export type DeleteMustHaveParams = __Infer<typeof DeleteMustHaveReducer>;
export type DeletePhaseParams = __Infer<typeof DeletePhaseReducer>;
export type DeletePhaseContextParams = __Infer<typeof DeletePhaseContextReducer>;
export type DeletePlanParams = __Infer<typeof DeletePlanReducer>;
export type DeletePlanSummaryParams = __Infer<typeof DeletePlanSummaryReducer>;
export type DeletePlanTaskParams = __Infer<typeof DeletePlanTaskReducer>;
export type DeleteProjectParams = __Infer<typeof DeleteProjectReducer>;
export type DeleteProjectStateParams = __Infer<typeof DeleteProjectStateReducer>;
export type DeleteRequirementParams = __Infer<typeof DeleteRequirementReducer>;
export type DeleteResearchParams = __Infer<typeof DeleteResearchReducer>;
export type DeleteVerificationParams = __Infer<typeof DeleteVerificationReducer>;
export type InsertMustHaveParams = __Infer<typeof InsertMustHaveReducer>;
export type InsertPhaseParams = __Infer<typeof InsertPhaseReducer>;
export type InsertPhaseContextParams = __Infer<typeof InsertPhaseContextReducer>;
export type InsertPlanParams = __Infer<typeof InsertPlanReducer>;
export type InsertPlanSummaryParams = __Infer<typeof InsertPlanSummaryReducer>;
export type InsertPlanTaskParams = __Infer<typeof InsertPlanTaskReducer>;
export type InsertProjectParams = __Infer<typeof InsertProjectReducer>;
export type InsertRequirementParams = __Infer<typeof InsertRequirementReducer>;
export type InsertResearchParams = __Infer<typeof InsertResearchReducer>;
export type InsertVerificationParams = __Infer<typeof InsertVerificationReducer>;
export type SeedProjectParams = __Infer<typeof SeedProjectReducer>;
export type UpdateMustHaveParams = __Infer<typeof UpdateMustHaveReducer>;
export type UpdatePhaseParams = __Infer<typeof UpdatePhaseReducer>;
export type UpdatePhaseContextParams = __Infer<typeof UpdatePhaseContextReducer>;
export type UpdatePlanParams = __Infer<typeof UpdatePlanReducer>;
export type UpdatePlanSummaryParams = __Infer<typeof UpdatePlanSummaryReducer>;
export type UpdatePlanTaskParams = __Infer<typeof UpdatePlanTaskReducer>;
export type UpdateProjectParams = __Infer<typeof UpdateProjectReducer>;
export type UpdateRequirementParams = __Infer<typeof UpdateRequirementReducer>;
export type UpdateResearchParams = __Infer<typeof UpdateResearchReducer>;
export type UpdateVerificationParams = __Infer<typeof UpdateVerificationReducer>;
export type UpsertConfigParams = __Infer<typeof UpsertConfigReducer>;
export type UpsertContinueHereParams = __Infer<typeof UpsertContinueHereReducer>;
export type UpsertProjectStateParams = __Infer<typeof UpsertProjectStateReducer>;

