// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  gitRemoteUrl: __t.string(),
  name: __t.string(),
  description: __t.string(),
  coreValue: __t.string(),
  constraints: __t.string(),
  context: __t.string(),
  keyDecisions: __t.string(),
};
