// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  projectId: __t.u64().name("project_id"),
  milestoneId: __t.u64().name("milestone_id"),
  auditStatus: __t.string().name("audit_status"),
  requirementScores: __t.string().name("requirement_scores"),
  integrationScores: __t.string().name("integration_scores"),
  flowScores: __t.string().name("flow_scores"),
  techDebtItems: __t.string().name("tech_debt_items"),
  roadmapContent: __t.string().name("roadmap_content"),
  requirementsContent: __t.string().name("requirements_content"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
