// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  phaseId: __t.u64().name("phase_id"),
  planNumber: __t.u64().name("plan_number"),
  type: __t.string(),
  wave: __t.u64(),
  dependsOn: __t.string().name("depends_on"),
  objective: __t.string(),
  autonomous: __t.bool(),
  requirements: __t.string(),
  status: __t.string(),
  content: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
