// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  planId: __t.u64().name("plan_id"),
  subsystem: __t.string(),
  tags: __t.string(),
  headline: __t.string(),
  accomplishments: __t.string(),
  deviations: __t.string(),
  files: __t.string(),
  decisions: __t.string(),
  dependencyGraph: __t.string().name("dependency_graph"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
