// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  projectId: __t.u64().name("project_id"),
  currentPhase: __t.string().name("current_phase"),
  currentPlan: __t.u64().name("current_plan"),
  currentTask: __t.u64().name("current_task"),
  lastActivity: __t.timestamp().name("last_activity"),
  lastActivityDescription: __t.string().name("last_activity_description"),
  velocityData: __t.string().name("velocity_data"),
  sessionLast: __t.string().name("session_last"),
  sessionStoppedAt: __t.string().name("session_stopped_at"),
  sessionResumeFile: __t.option(__t.string()).name("session_resume_file"),
  updatedAt: __t.timestamp().name("updated_at"),
});
