// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const CodebaseMap = __t.object("CodebaseMap", {
  id: __t.u64(),
  projectId: __t.u64(),
  docType: __t.string(),
  content: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type CodebaseMap = __Infer<typeof CodebaseMap>;

export const Config = __t.object("Config", {
  id: __t.u64(),
  projectId: __t.u64(),
  config: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Config = __Infer<typeof Config>;

export const ContinueHere = __t.object("ContinueHere", {
  id: __t.u64(),
  projectId: __t.u64(),
  phaseId: __t.u64(),
  taskNumber: __t.u64(),
  currentState: __t.string(),
  nextAction: __t.string(),
  context: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type ContinueHere = __Infer<typeof ContinueHere>;

export const DebugSession = __t.object("DebugSession", {
  id: __t.u64(),
  projectId: __t.u64(),
  bugDescription: __t.string(),
  hypotheses: __t.string(),
  checkpoints: __t.string(),
  timeline: __t.string(),
  status: __t.string(),
  resolutionNotes: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type DebugSession = __Infer<typeof DebugSession>;

export const Milestone = __t.object("Milestone", {
  id: __t.u64(),
  projectId: __t.u64(),
  version: __t.string(),
  name: __t.string(),
  shippedDate: __t.string(),
  phaseCount: __t.u64(),
  planCount: __t.u64(),
  requirementCount: __t.u64(),
  accomplishments: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Milestone = __Infer<typeof Milestone>;

export const MilestoneAudit = __t.object("MilestoneAudit", {
  id: __t.u64(),
  projectId: __t.u64(),
  milestoneId: __t.u64(),
  auditStatus: __t.string(),
  requirementScores: __t.string(),
  integrationScores: __t.string(),
  flowScores: __t.string(),
  techDebtItems: __t.string(),
  roadmapContent: __t.string(),
  requirementsContent: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type MilestoneAudit = __Infer<typeof MilestoneAudit>;

export const MustHave = __t.object("MustHave", {
  id: __t.u64(),
  planId: __t.u64(),
  truths: __t.string(),
  artifacts: __t.string(),
  keyLinks: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type MustHave = __Infer<typeof MustHave>;

export const Phase = __t.object("Phase", {
  id: __t.u64(),
  projectId: __t.u64(),
  number: __t.string(),
  name: __t.string(),
  slug: __t.string(),
  goal: __t.string(),
  status: __t.string(),
  dependsOn: __t.string(),
  successCriteria: __t.string(),
  isInserted: __t.bool(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Phase = __Infer<typeof Phase>;

export const PhaseContext = __t.object("PhaseContext", {
  id: __t.u64(),
  phaseId: __t.u64(),
  content: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type PhaseContext = __Infer<typeof PhaseContext>;

export const Plan = __t.object("Plan", {
  id: __t.u64(),
  phaseId: __t.u64(),
  planNumber: __t.u64(),
  type: __t.string(),
  wave: __t.u64(),
  dependsOn: __t.string(),
  objective: __t.string(),
  autonomous: __t.bool(),
  requirements: __t.string(),
  status: __t.string(),
  content: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Plan = __Infer<typeof Plan>;

export const PlanSummary = __t.object("PlanSummary", {
  id: __t.u64(),
  planId: __t.u64(),
  subsystem: __t.string(),
  tags: __t.string(),
  headline: __t.string(),
  accomplishments: __t.string(),
  deviations: __t.string(),
  files: __t.string(),
  decisions: __t.string(),
  dependencyGraph: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type PlanSummary = __Infer<typeof PlanSummary>;

export const PlanTask = __t.object("PlanTask", {
  id: __t.u64(),
  planId: __t.u64(),
  taskNumber: __t.u64(),
  type: __t.string(),
  description: __t.string(),
  status: __t.string(),
  commitHash: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type PlanTask = __Infer<typeof PlanTask>;

export const Project = __t.object("Project", {
  id: __t.u64(),
  gitRemoteUrl: __t.string(),
  name: __t.string(),
  description: __t.string(),
  coreValue: __t.string(),
  constraints: __t.string(),
  context: __t.string(),
  keyDecisions: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Project = __Infer<typeof Project>;

export const ProjectState = __t.object("ProjectState", {
  id: __t.u64(),
  projectId: __t.u64(),
  currentPhase: __t.string(),
  currentPlan: __t.u64(),
  currentTask: __t.u64(),
  lastActivity: __t.timestamp(),
  lastActivityDescription: __t.string(),
  velocityData: __t.string(),
  sessionLast: __t.string(),
  sessionStoppedAt: __t.string(),
  sessionResumeFile: __t.option(__t.string()),
  updatedAt: __t.timestamp(),
});
export type ProjectState = __Infer<typeof ProjectState>;

export const Requirement = __t.object("Requirement", {
  id: __t.u64(),
  projectId: __t.u64(),
  category: __t.string(),
  number: __t.string(),
  description: __t.string(),
  status: __t.string(),
  phaseNumber: __t.string(),
  milestoneVersion: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Requirement = __Infer<typeof Requirement>;

export const Research = __t.object("Research", {
  id: __t.u64(),
  phaseId: __t.u64(),
  domain: __t.string(),
  confidence: __t.string(),
  content: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Research = __Infer<typeof Research>;

export const SessionCheckpoint = __t.object("SessionCheckpoint", {
  id: __t.u64(),
  projectId: __t.u64(),
  phaseId: __t.u64(),
  phaseContext: __t.string(),
  completedWork: __t.string(),
  remainingWork: __t.string(),
  decisions: __t.string(),
  blockers: __t.string(),
  nextAction: __t.string(),
  mentalContext: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type SessionCheckpoint = __Infer<typeof SessionCheckpoint>;

export const Todo = __t.object("Todo", {
  id: __t.u64(),
  projectId: __t.u64(),
  title: __t.string(),
  area: __t.string(),
  problem: __t.string(),
  solutionHints: __t.string(),
  fileRefs: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Todo = __Infer<typeof Todo>;

export const Verification = __t.object("Verification", {
  id: __t.u64(),
  phaseId: __t.u64(),
  status: __t.string(),
  score: __t.u64(),
  content: __t.string(),
  recommendedFixes: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Verification = __Infer<typeof Verification>;

